


server:
  servlet:
    container: tomcat
redis:
  host: localhost
  port: 6379

spring:
  application:
    name: gateway-service






  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter



            - name: CircuitBreaker
              args:
                name: retailBankCircuitBreaker
                fallbackUri: forward:/fallback/retailBankFallback

        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: retailDepartmentServiceBreaker
                fallbackUri: forward:/fallback/departmentserviceFallback

        - id: IDENITY-SERVICE
          uri: lb://IDENITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: identityservicefallback
                fallbackUri: forward:/fallback/identityservicefallback


    config:
      enabled: true
      uri: http://localhost:9292